config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users

  resources :users do
    resources :purchases, only: [:new, :create, :show]
    resources :net_worths, only: [:new, :show, :create]
    resources :smokes, only: [:new, :create, :update, :index]
  end
end

app/models/cigarette.rb
class Cigarette < ActiveRecord::Base
  belongs_to :location
  belongs_to :year

  validates :cost,
    presence: true,
    numericality: true

  validates :location_id,
    presence: true
end

app/models/fetch_cigarette_costs.rb
class FetchCigaretteCosts
  attr_accessor :cigarette
  def initalize
    @cigarettes
    @cigarette
    @line
    @location
    @year
    @years
  end

  def find_or_create_data
    create_data if !(Cigarette.count == 96)

    split_by_years

    @years
  end

  def create_data
    file_path = './lib/assets/costs_by_state_2014.txt'
    File.readlines(file_path).each_with_index do |line, index|
      line.gsub!(/last year/, '') if index == 0

      @line = line.gsub!(/(\(|\):|=)|\n/, '')

      format_data

      create_new_cigarettes
    end
  end

  def format_data
    @data = {}

    line = @line.split('$')

    @data['rank'] = line[0].split[0].gsub!('.', '')
    @data['state'] = line[0].split[1..-1].join(' ')
    @data['2013_cost'] = line[1].to_f
    @data['2014_cost'] = line[2].split[0].to_f
    @data['change'] = line[2].split[1]
  end

  def create_new_cigarettes
    @location = Location.find_by(state: @data['state'])

    @location = Location.create!(state: @data['state']) if !@location

    create_2013_cigarette

    create_2014_cigarette
  end

  def create_2013_cigarette
    find_or_create_year(2013)

    cig_params = { cost: @data['2013_cost'],
                   location_id: @location.id,
                   year_id: @year.id
                 }

    Cigarette.create!(cig_params)
  end

  def create_2014_cigarette
    find_or_create_year(2014)

    cig_params = { cost: @data['2014_cost'],
                   location_id: @location.id,
                   rank: @data['rank'],
                   change: @data['change'],
                   year_id: @year.id
                 }

    Cigarette.create!(cig_params)
  end

  def split_by_years
    @years = {}

    year_2013 = Year.where(year: '2013').first
    year_2014 = Year.where(year: '2014').first

    @years['2013'] = Cigarette.where(year_id: year_2013.id)
    @years['2014'] = Cigarette.where(year_id: year_2014.id)
  end

  def find_or_create_year(year)
    @year = Year.where(year: year).first
    @year = Year.create!(year: year) if !@year
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :cigarettes
  has_many :users
end

app/models/location_helper.rb
class LocationHelper
  def initialize
    @locations = Location.all
  end

  def states_list
    @locations.map do |location|
      location
    end
  end
end

app/models/net_worth.rb
class NetWorth < ActiveRecord::Base
  belongs_to :user
  validates :income,
    presence: true,
    numericality: true

end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :user
end

app/models/smoke.rb
class Smoke < ActiveRecord::Base
  belongs_to :user
end

app/models/streak.rb
class Streak < ActiveRecord::Base
  belongs_to :user

  def update_streak
    streak_params = {}

    #increment slump
    streak_params[:current_slump] = current_slump + 1

    #record longest_streak
    if current_streak > longest_streak
      streak_params[:longest_streak] = current_streak
    end

    #reset current_streak
    streak_params[:current_streak] = 0

    #record longest_slump
    if current_slump + 1 > longest_slump
      streak_params[:longest_slump] = current_slump + 1
    end

    update_attributes(streak_params)
    save
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :purchases
  has_many :net_worths
  has_many :smokes
  has_one :streak
  belongs_to :location

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def smoke_cost(time_period)
    cost_of_smoke = location.cigarettes.last.cost/20
    smoke_count = fetch_smoke_records_count(time_period)

    (smoke_count * cost_of_smoke).round(2)
  end

  def health_cost(time_period)
    health_cost = location.cigarettes.last.health_cost
    smoke_count = fetch_smoke_records_count(time_period)

    (smoke_count * health_cost).to_i
  end

  def fetch_smoke_records_count(time_period)
    case time_period
    when 'daily'
      smokes = self.smokes.where(
        "created_at > ? AND created_at < ?",
        DateTime.now.beginning_of_day, DateTime.now.end_of_day
      )
    when 'weekly'
      smokes = self.smokes.where(
        "created_at > ? AND created_at < ?",
        DateTime.now.beginning_of_week, DateTime.now.end_of_week
      )
    when 'monthly'
      smokes = self.smokes.where(
        "created_at > ? AND created_at < ?",
        DateTime.now.beginning_of_month, DateTime.now.end_of_month
      )
    when 'annually'
      smokes = self.smokes.where(
        "created_at > ? AND created_at < ?",
        DateTime.now.beginning_of_year, DateTime.now.end_of_year
      )
    when 'all-time'
      smokes = self.smokes
    end
    smokes.count
  end
end

app/models/user_cigarette.rb
class UserCigarette < ActiveRecord::Base
  belongs_to :user
  belongs_to :cigarette
end

app/models/year.rb
class Year < ActiveRecord::Base
  has_many :cigarettes

  validates :year, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 before_filter :configure_permitted_parameters, if: :devise_controller?

 protected

 def configure_permitted_parameters
  devise_parameter_sanitizer.for(:sign_up) << [:username, :location_id]
 end
end

app/controllers/cigarettes_controller.rb
class CigarettesController < ApplicationController
  def index
    @cigarettes = FetchCigaretteCosts.new.find_or_create_data
    # order by cost
    # @cigarettes['2013'].sort_by { |i| i.cost }
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @user = current_user
    render :index, layout: true
  end
end

app/controllers/net_worths_controller.rb
class NetWorthsController < ApplicationController
  def new
    @net_worth = NetWorth.new
    @user = current_user
  end

  def create
    binding.pry
    @user = current_user
    @net_worth = NetWorth.create!(income: params[:net_worth][:income],
                                  user_id: @user.id)

    render :show
  end

  def show

  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def new
    @purchase = Purchase.new
    @user = current_user
  end

  def create
    @purchase = Purchase.new
    @user = current_user
    location = Location.find(@user.location_id)

    cig = Cigarette.where(location: location, year_id: 2).first
    cost = cig.cost
    @user.purchases.create!(cost: cost)

    render :show
  end

  def show

  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def create

  end
end

app/controllers/smokes_controller.rb
class SmokesController < ApplicationController
  respond_to :json, :html

  def new
    @user = current_user
    @smoke = @user.smokes.new
  end

  def create
    @user = current_user
    @user.smokes.create(decision: true)

    @user.streak ||= Streak.new
    @user.streak.update_streak

    redirect_to root_path
  end

  def index
    @user = current_user
    # @smokes = current_user.smokes
    @smokes = current_user.smokes.group_by_day(:created_at).count.map do |smoke|
      result = {}

      result[:date] = smoke[0].to_date
      result[:count] = smoke[1]

      result
    end

    respond_to do |format|
    #   binding.pry
    #   format.json { render json: @smokes }
    end
  end

  def update
    @user = current_user
    @smoke = @user.smokes.find()
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/smokes_helper.rb
module SmokesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LetsQuit</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <link href='http://fonts.googleapis.com/css?family=Quicksand:300' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

  <section id="decision">
    <% if @user %>
      <%= render partial: "/streaks/streak" %>
    <% else %>
      <div id="sign-in-sign-up-msg">
        <h3 class="text-center">
          <span><%= link_to 'Please sign-in', new_user_session_path, class: 'white-text' %></span>
          or
          <span><%= link_to 'create a new account', new_user_registration_path, class: 'white-text' %></span>
        </h3>
      </div>
    <% end %>
    <% if @user %>
      <% 3.times do %>
        </br>
      <% end %>
      <div class="row">
        <div class="small-12 medium-12 large-9 large-centered columns">
          <h5 class="mission-statement text-center">Each time we light up a cigarette, we make a decision, conscious or unconscious.</h5>
          <h5 class="mission-statement text-center">Whether we crave a smoke everytime it rains or when we become stressed,</h5>
          <h5 class="mission-statement text-center">
          JustQuit is here to help each decision become a conscious decision.
          </h5>
        </div>
      </div>
      <% 3.times do %>
        </br>
      <% end %>

      <div class="small-6 medium-6 large-6 columns">
        <%= link_to "Smoke", user_smokes_path(@user), method: 'post', class: "button right", id: "decision-smoke" %>
      </div>

      <div class="small-6 medium-6 large-6 columns left">
        <%= link_to "Not to Smoke", user_smokes_path(@user), method: 'post', class: "button left", id: "decision-not-smoke" %>
      </div>
    <% end %>
  </section>

    <section id="main-screen">
      <br><br>
      <% if @user && !@user.smokes.empty? %>
        <%= render partial: "/partials/user_spending" %>
      <% end %>
    </section>

    <div>
      <input type="button" class="button large-12 columns red-text" id="chart-button" value="View Chart">
    </div>

    <% 3.times do %>
      </br>
    <% end %>

    <% if @user %>
      <div class="row">
        <div class="small-12 small-centered medium-12 medium-centerd large-12 large-centered">
          <section id="charts-container" style="width:100%; height:400px;">
          </section>
        </div>
      </div>
    <% end %>


  <%= javascript_include_tag 'application' %>

  <%= yield :extra_footer %>
</body>
</html>

app/views/purchases/new.html.erb
<div class="small-12 columns purchase-button">
  <%= form_for [@user, @purchase] do |f| %>
    <%= f.submit "Post Purchase", class: "button alert" %>
  <% end %>
</div>

app/views/purchases/show.html.erb
<div class="small-12 columns">
  <div class="small-2 columns transactions">
    <ul>
      </br>
        <% sum = 0 %>
        <% start_date = nil %>
        <% end_date = nil %>
      <% current_user.purchases.each_with_index do |purchase, index| %>
        <% start_date ||= purchase.created_at %>
        <% end_date = purchase.created_at if index == current_user.purchases.count - 1 %>

        <li><%= purchase.created_at %> <%= purchase.cost %></li></br>

        <% sum += purchase.cost %>

      <% end %>

      <% total_seconds = (end_date - start_date) %>
      <% total_minutes = total_seconds/60 %>
      <% total_hours = total_seconds %>
    </ul>
  </div>

  <div class="small-10 columns">
    </br>
    <h2>In the past <%= total_minutes.round %> minutes, you bought <%= current_user.purchases.count %> packs of cigarettes at an cost of <%= current_user.purchases.first.cost %>
    </h2>

    </br>

    <h2>As a result, you spent $<%= sum.round(2) %> in <%= total_minutes.round %> minutes</h2>

    </br>
    <h1>
      <% income = 0 %>
      <% NetWorth.where(user_id: current_user.id).each do |worth| %>

        <% income += worth.income %>
      <% end %>

      You spent <%= ((sum / income) * 100.to_f).round(2) %>% of your money on cigarettes
    </h1>
  </div>
</div>

app/views/streaks/_streak.html.erb
<% if @user.smokes.any? %>
  <section id="streak-bar">
    <div class="left-bar">
      <h5 class="text-center">Cigarettes Smoked Today: <%= @user.fetch_smoke_records_count('daily') %></h5>
    </div>
    <div class="right-bar">
      <h5 class="text-center">Cigarettes Smoked Lifetime: <%= @user.smokes.count %></h5>
    </div>
  </section>
<% end %>