config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users

  resources :users do
    resources :purchases, only: [:new, :create, :show]
    resources :net_worths, only: [:new, :show, :create]
    resources :smokes, only: [:new, :create, :update, :index]
  end
end

app/models/cigarette.rb
class Cigarette < ActiveRecord::Base
  belongs_to :location
  belongs_to :year

  validates :cost,
    presence: true,
    numericality: true

  validates :location_id,
    presence: true
end

app/models/fetch_cigarette_costs.rb
class FetchCigaretteCosts
  attr_accessor :cigarette
  def initalize
    @cigarettes
    @cigarette
    @line
    @location
    @year
    @years
  end

  def find_or_create_data
    create_data if !(Cigarette.count == 96)

    split_by_years

    @years
  end

  def create_data
    file_path = './lib/assets/costs_by_state_2014.txt'
    File.readlines(file_path).each_with_index do |line, index|
      line.gsub!(/last year/, '') if index == 0

      @line = line.gsub!(/(\(|\):|=)|\n/, '')

      format_data

      create_new_cigarettes
    end
  end

  def format_data
    @data = {}

    line = @line.split('$')

    @data['rank'] = line[0].split[0].gsub!('.', '')
    @data['state'] = line[0].split[1..-1].join(' ')
    @data['2013_cost'] = line[1].to_f
    @data['2014_cost'] = line[2].split[0].to_f
    @data['change'] = line[2].split[1]
  end

  def create_new_cigarettes
    @location = Location.find_by(state: @data['state'])

    @location = Location.create!(state: @data['state']) if !@location

    create_2013_cigarette

    create_2014_cigarette
  end

  def create_2013_cigarette
    find_or_create_year(2013)

    cig_params = { cost: @data['2013_cost'],
                   location_id: @location.id,
                   year_id: @year.id
                 }

    Cigarette.create!(cig_params)
  end

  def create_2014_cigarette
    find_or_create_year(2014)

    cig_params = { cost: @data['2014_cost'],
                   location_id: @location.id,
                   rank: @data['rank'],
                   change: @data['change'],
                   year_id: @year.id
                 }

    Cigarette.create!(cig_params)
  end

  def split_by_years
    @years = {}

    year_2013 = Year.where(year: '2013').first
    year_2014 = Year.where(year: '2014').first

    @years['2013'] = Cigarette.where(year_id: year_2013.id)
    @years['2014'] = Cigarette.where(year_id: year_2014.id)
  end

  def find_or_create_year(year)
    @year = Year.where(year: year).first
    @year = Year.create!(year: year) if !@year
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :cigarettes
  has_many :users
end

app/models/location_helper.rb
class LocationHelper
  def initialize
    @locations = Location.all
  end

  def states_list
    @locations.map do |location|
      location
    end
  end
end

app/models/net_worth.rb
class NetWorth < ActiveRecord::Base
  belongs_to :user
  validates :income,
    presence: true,
    numericality: true

end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :user
end

app/models/smoke.rb
class Smoke < ActiveRecord::Base
  belongs_to :user
end

app/models/streak.rb
class Streak < ActiveRecord::Base
  belongs_to :user

  def update_streak
    streak_params = {}

    #increment slump
    streak_params[:current_slump] = current_slump + 1

    #record longest_streak
    if current_streak > longest_streak
      streak_params[:longest_streak] = current_streak
    end

    #reset current_streak
    streak_params[:current_streak] = 0

    #record longest_slump
    if current_slump + 1 > longest_slump
      streak_params[:longest_slump] = current_slump + 1
    end

    update_attributes(streak_params)
    save
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :purchases
  has_many :net_worths
  has_many :smokes
  has_one :streak
  belongs_to :location

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def smoke_cost(time_period)
    cost_of_smoke = location.cigarettes.last.cost/20
    smoke_count = fetch_smoke_records_count(time_period)

    (smoke_count * cost_of_smoke).round(2)
  end

  def health_cost(time_period)
    health_cost = location.cigarettes.last.health_cost
    smoke_count = fetch_smoke_records_count(time_period)

    (smoke_count * health_cost).to_i
  end

  def fetch_smoke_records_count(time_period)
    case time_period
    when 'daily'
      smokes = self.smokes.where(
        "created_at > ? AND created_at < ?",
        DateTime.now.beginning_of_day, DateTime.now.end_of_day
      )
    when 'weekly'
      smokes = self.smokes.where(
        "created_at > ? AND created_at < ?",
        DateTime.now.beginning_of_week, DateTime.now.end_of_week
      )
    when 'monthly'
      smokes = self.smokes.where(
        "created_at > ? AND created_at < ?",
        DateTime.now.beginning_of_month, DateTime.now.end_of_month
      )
    when 'annually'
      smokes = self.smokes.where(
        "created_at > ? AND created_at < ?",
        DateTime.now.beginning_of_year, DateTime.now.end_of_year
      )
    when 'all-time'
      smokes = self.smokes
    end
    smokes.count
  end
end

app/models/user_cigarette.rb
class UserCigarette < ActiveRecord::Base
  belongs_to :user
  belongs_to :cigarette
end

app/models/year.rb
class Year < ActiveRecord::Base
  has_many :cigarettes

  validates :year, presence: true
end

app/controllers/cigarettes_controller.rb
class CigarettesController < ApplicationController
  def index
    @cigarettes = FetchCigaretteCosts.new.find_or_create_data
    # order by cost
    # @cigarettes['2013'].sort_by { |i| i.cost }
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @user = current_user
    render :index, layout: true
  end
end

app/controllers/net_worths_controller.rb
class NetWorthsController < ApplicationController
  def new
    @net_worth = NetWorth.new
    @user = current_user
  end

  def create
    binding.pry
    @user = current_user
    @net_worth = NetWorth.create!(income: params[:net_worth][:income],
                                  user_id: @user.id)

    render :show
  end

  def show

  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def new
    @purchase = Purchase.new
    @user = current_user
  end

  def create
    @purchase = Purchase.new
    @user = current_user
    location = Location.find(@user.location_id)

    cig = Cigarette.where(location: location, year_id: 2).first
    cost = cig.cost
    @user.purchases.create!(cost: cost)

    render :show
  end

  def show

  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def create

  end
end

app/controllers/smokes_controller.rb
class SmokesController < ApplicationController
  respond_to :json, :html

  def new
    @user = current_user
    @smoke = @user.smokes.new
  end

  def create
    @user = current_user
    @user.smokes.create(decision: true)

    @user.streak ||= Streak.new
    @user.streak.update_streak

    redirect_to root_path
  end

  def index
    @user = current_user
    # @smokes = current_user.smokes
    @smokes = current_user.smokes.group_by_day(:created_at).count.map do |smoke|
      result = {}

      result[:date] = smoke[0].to_date
      result[:count] = smoke[1]

      result
    end

    respond_to do |format|
    #   binding.pry
    #   format.json { render json: @smokes }
    end
  end

  def update
    @user = current_user
    @smoke = @user.smokes.find()
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/smokes_helper.rb
module SmokesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JustQuit</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Press+Start+2P">
  <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">JustQuit</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <!-- <li><%= link_to 'Add Income', new_user_net_worth_path(current_user) %></li>

          <li><%= link_to 'Add a purchase', new_user_purchase_path(current_user) %></li> -->

          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>
  <%= javascript_include_tag 'application' %>
  <script src="http://code.highcharts.com/highcharts.js"></script>
  <%= yield :extra_footer %>
</body>
</html>

app/views/partials/_user_spending.html.erb
<% if @user.smokes.any? %>
  <section id="cost-container">
    <section id="cost-today">
        <h4>You've smoked $<%= @user.smoke_cost('daily') %> worth of cigarettes today</h4>
        <br>
        <h4><%= @user.fetch_smoke_records_count('daily') %> cigarettes have taken <%= @user.health_cost('daily') %> minutes off your life</h4>
    </section>

    <section id="cost-all-time">
        <h4>Since <%= "#{@user.smokes.first.created_at.month}/#{@user.smokes.first.created_at.day}/#{@user.smokes.first.created_at.year}" %>, you've smoked $<%= @user.smoke_cost('all-time') %> worth of cigarettes</h4>
        <br>
        <h4><%= @user.fetch_smoke_records_count('all-time') %> cigarettes have taken <%= @user.health_cost('all-time') %> minutes off your life</h4>
    </section>
  </section>
<% end %>